
version: 0.2

#run-as:ubuntu

phases:
  install:
    runtime-versions:
      python: 3.7

  build:
    commands:
      - npm -v
      - cd StepFunctions/TestFunction
      - npm init -y
      - npm install -g serverless
      #- npm install --save-dev serverless-step-functions
      #- npm install --save-dev serverless-pseudo-parameters
      #- npm install --save serverless-apigateway-plugin
      - npm install
      #- npm audit fix
      #- npm ls --depth=0
     # - sls plugin install -n serverless-apigateway-service-proxy
      - sls plugin list|grep step
      - serverless -v
      #- npm list --depth=0
      #- sls plugin install -n serverless-python-requirements
      - sls config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
      - sls deploy --stage $TARGET_ENV