service: TestFunctions

#plugins:
#  - serverless-pseudo-parameters
#  - serverless-apigateway-plugin
#  - serverless-apigateway-service-proxy
provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  stage: ${opt:stage, 'Development'}
  resourcePolicy:
  - Effect: Allow
    Principal: '*'
    Action: execute-api:Invoke
    Resource:
      - execute-api:/*/*/*
    Condition:
      IpAddress:
        aws:SourceIp:
          - '61.21.109.72/32'
  #apiKeys:
  #  - test_api_keys

#custom:
#  Development:
#    sns_arn: "arn:aws:sns:us-east-2:781667190002:DevelopmentNotification"
#  Staging:
#    sns_arn: "arn:aws:sns:us-east-2:781667190002:StagingNotification"
#  Production:
#    sns_arn: "arn:aws:sns:us-east-2:781667190002:ProductionNotification"

configValidationMode: error

functions:
  Function1:
    name: ${self:provider.stage}TestFunctions
    handler: handler.lambda_handler
    events:
      #- sns: ${self:custom.${self:provider.stage}.sns_arn}
      - http:
          integration: lambda
          path: hello
          method: post

      
    environment:
      slackChannel: hogeo_no_slack_channel
      HookUrl: https://hooks.slack.com/services/xxxxxxxxxxx/xxxxxxxxxxxx/xxxxxxxxxxxxx